spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant?createDatabaseIfNotExist=true  #This is the generic format of the connection URL + Creates the database given in the URL if it doesn't yet exist.
    serverTimezone: UTC #Override detection/mapping of time zone. Used when time zone from server doesn't map to Java time zone
    username: root
    password: 123456789